name: MOBS
main: Palk\MOBS\Mobs
version: "1.0 Beta"
api: 2.0.0
load: POSTWORLD
author: PalkiaDude
commands:
 mobs:
  usage: false
  description: ""
  aliases: [ent, entity]
  permission: MOBS.command
